{% set name = "pyfluxconserving" %}
{% set version = "0.0.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 28a0c3cc2d531fada378d67e737595349f1bf00033c9d99a2c174e3ca0c83a71

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - matplotlib
    - numpy
    - pip
    - python
  run:
    - matplotlib
    - numpy
    - python

test:
  imports:
    - pyfluxconserving

about:
  home: "https://github.com/neutrinomuon/Pyfluxconserving"
  license_file: 'LICENSE.txt'
  summary: "Flux-conserving legacy routines in Fortran and Python"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - neutrinomuon
